
'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { BookOpen, Sparkles, Download, Share2, ChevronDown, ChevronUp } from 'lucide-react'
import axios from 'axios'

interface StudyGuide {
  _id?: string
  homeworkId: string
  title: string
  summary: string
  keyPoints: string[]
  flashcards: Array<{
    question: string
    answer: string
  }>
  createdAt?: string
}

interface StudyGuideGeneratorProps {
  homework: {
    _id: string
    title: string
    subject: string
    description: string
  }
  apiUrl: string
  onStudyGuideCreated?: (studyGuide: StudyGuide) => void
}

export default function StudyGuideGenerator({ 
  homework, 
  apiUrl, 
  onStudyGuideCreated 
}: StudyGuideGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false)
  const [studyGuide, setStudyGuide] = useState<StudyGuide | null>(null)
  const [error, setError] = useState<string>('')
  const [expandedSections, setExpandedSections] = useState({
    summary: true,
    keyPoints: true,
    flashcards: true
  })

  const generateStudyGuide = async () => {
    setIsGenerating(true)
    setError('')

    try {
      const response = await axios.post(`${apiUrl}/api/study/generate`, {
        homeworkId: homework._id,
        title: homework.title,
        subject: homework.subject,
        description: homework.description
      }, {
        timeout: 60000,
        headers: {
          'Content-Type': 'application/json',
        }
      })

      const newStudyGuide = response.data
      setStudyGuide(newStudyGuide)
      onStudyGuideCreated?.(newStudyGuide)
    } catch (error) {
      console.error('Error generating study guide:', error)
      setError('Failed to generate study guide. Please try again.')
    } finally {
      setIsGenerating(false)
    }
  }

  const downloadStudyGuide = () => {
    if (!studyGuide) return

    const content = `
# ${studyGuide.title} - Study Guide

## Summary
${studyGuide.summary}

## Key Points
${studyGuide.keyPoints.map(point => `• ${point}`).join('\n')}

## Flashcards
${studyGuide.flashcards.map((card, index) => `
${index + 1}. **Q:** ${card.question}
   **A:** ${card.answer}
`).join('\n')}

Generated by SMS Homework Tracker
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${studyGuide.title.replace(/\s+/g, '_')}_Study_Guide.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const toggleSection = (section: keyof typeof expandedSections) => {
    setExpandedSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }))
  }

  return (
    <div className="bg-dark-card border border-dark-border rounded-lg p-6">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold text-white flex items-center">
          <BookOpen className="w-5 h-5 mr-2" />
          Study Guide
        </h3>
        
        {studyGuide && (
          <div className="flex space-x-2">
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={downloadStudyGuide}
              className="p-2 bg-blue-500/20 text-blue-400 rounded-lg hover:bg-blue-500/30 transition-colors"
              title="Download Study Guide"
            >
              <Download className="w-4 h-4" />
            </motion.button>
          </div>
        )}
      </div>

      {!studyGuide ? (
        <div className="text-center py-8">
          <Sparkles className="w-12 h-12 text-purple-400 mx-auto mb-4" />
          <h4 className="text-white font-medium mb-2">Generate AI Study Guide</h4>
          <p className="text-dark-text-secondary text-sm mb-4">
            Create a comprehensive study guide with key points and flashcards using AI
          </p>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={generateStudyGuide}
            disabled={isGenerating}
            className="px-6 py-3 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-lg font-medium hover:from-purple-600 hover:to-pink-600 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isGenerating ? (
              <div className="flex items-center">
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2"></div>
                Generating...
              </div>
            ) : (
              'Generate Study Guide'
            )}
          </motion.button>
        </div>
      ) : (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-4"
        >
          {/* Summary Section */}
          <div className="border border-dark-border rounded-lg overflow-hidden">
            <button
              onClick={() => toggleSection('summary')}
              className="w-full flex items-center justify-between p-4 bg-dark-border/50 hover:bg-dark-border transition-colors"
            >
              <h4 className="text-white font-medium">Summary</h4>
              {expandedSections.summary ? (
                <ChevronUp className="w-4 h-4 text-dark-text-secondary" />
              ) : (
                <ChevronDown className="w-4 h-4 text-dark-text-secondary" />
              )}
            </button>
            <AnimatePresence>
              {expandedSections.summary && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="p-4"
                >
                  <p className="text-dark-text-secondary text-sm leading-relaxed">
                    {studyGuide.summary}
                  </p>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Key Points Section */}
          <div className="border border-dark-border rounded-lg overflow-hidden">
            <button
              onClick={() => toggleSection('keyPoints')}
              className="w-full flex items-center justify-between p-4 bg-dark-border/50 hover:bg-dark-border transition-colors"
            >
              <h4 className="text-white font-medium">Key Points</h4>
              {expandedSections.keyPoints ? (
                <ChevronUp className="w-4 h-4 text-dark-text-secondary" />
              ) : (
                <ChevronDown className="w-4 h-4 text-dark-text-secondary" />
              )}
            </button>
            <AnimatePresence>
              {expandedSections.keyPoints && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="p-4"
                >
                  <ul className="space-y-2">
                    {studyGuide.keyPoints.map((point, index) => (
                      <li key={index} className="flex items-start text-dark-text-secondary text-sm">
                        <span className="text-purple-400 mr-2">•</span>
                        {point}
                      </li>
                    ))}
                  </ul>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Flashcards Section */}
          <div className="border border-dark-border rounded-lg overflow-hidden">
            <button
              onClick={() => toggleSection('flashcards')}
              className="w-full flex items-center justify-between p-4 bg-dark-border/50 hover:bg-dark-border transition-colors"
            >
              <h4 className="text-white font-medium">Flashcards ({studyGuide.flashcards.length})</h4>
              {expandedSections.flashcards ? (
                <ChevronUp className="w-4 h-4 text-dark-text-secondary" />
              ) : (
                <ChevronDown className="w-4 h-4 text-dark-text-secondary" />
              )}
            </button>
            <AnimatePresence>
              {expandedSections.flashcards && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="p-4"
                >
                  <div className="space-y-3">
                    {studyGuide.flashcards.map((card, index) => (
                      <div key={index} className="bg-dark-bg p-3 rounded-lg border border-dark-border">
                        <p className="text-white text-sm font-medium mb-2">
                          <span className="text-purple-400">Q:</span> {card.question}
                        </p>
                        <p className="text-dark-text-secondary text-sm">
                          <span className="text-green-400">A:</span> {card.answer}
                        </p>
                      </div>
                    ))}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </motion.div>
      )}

      {error && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="mt-4 p-3 bg-red-500/20 border border-red-500/50 rounded-lg"
        >
          <p className="text-red-400 text-sm">{error}</p>
        </motion.div>
      )}
    </div>
  )
}
